# Generated by Django 3.2.7 on 2021-09-17 05:39

import booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('last_booking', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookingStatus',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.CharField(default=booking.models.booking_id_generator, max_length=8, primary_key=True, serialize=False)),
                ('date_of_journey', models.CharField(default=booking.models.get_booking_date, max_length=20)),
                ('booking_date', models.DateField(auto_now=True)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.trains')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ('booking_date',),
            },
        ),
    ]
